language: python
group: edge
arch: arm64-graviton2
python:
  - "3.8"
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
