# Generated by Django 3.1.3 on 2020-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201126_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='to be filled', max_length=255),
            preserve_default=False,
        ),
    ]
