# Generated by Django 3.1.4 on 2020-12-02 15:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201202_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('videoURL', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('videoLatitude', models.FloatField(null=True)),
                ('videoLongitude', models.FloatField(null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=255)),
                ('profilePicture', models.URLField()),
                ('profileARR', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('is_private', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastLoggedin', models.DateTimeField(blank=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('photoURL', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('photoLatitude', models.FloatField(null=True)),
                ('photoLongitude', models.FloatField(null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('likeDate', models.DateTimeField(auto_now_add=True)),
                ('photoId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
            ],
        ),
    ]
