# Generated by Django 3.1.4 on 2020-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201202_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastLoggedin',
            field=models.DateTimeField(),
        ),
    ]
