# Generated by Django 3.1.4 on 2020-12-02 16:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201202_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='photoId',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('postCaption', models.TextField()),
                ('postHashTags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('postLocation', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField(editable=False)),
                ('postTag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('postImage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
                ('postVideo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.video')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('followId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('followers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='postId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
            preserve_default=False,
        ),
    ]
