# Generated by Django 3.1.4 on 2020-12-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201202_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=150)),
                ('postID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReplyLike',
            fields=[
                ('commentReplyLikeId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('commentReplyId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('commentReplyId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('commentReply', models.CharField(max_length=150)),
                ('commentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('commentLikeId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('commentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
