# Generated by Django 3.1.4 on 2020-12-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comment_commentlike_commentreply_commentreplylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('storyId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('storyDate', models.DateTimeField(auto_now=True)),
                ('storyImage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
                ('storyVideo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.video')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('storyViewId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('storyId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.story')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
