# Generated by Django 3.1.4 on 2020-12-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_story_storyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyImage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
        ),
    ]
