# Generated by Django 3.1.4 on 2020-12-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201202_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyImage',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
        ),
    ]
