# Generated by Django 3.1.4 on 2020-12-03 05:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201202_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoURL',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), size=None),
        ),
    ]
