# Generated by Django 3.1.4 on 2020-12-03 05:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201203_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileARR',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), size=None),
        ),
    ]
