# Generated by Django 3.1.4 on 2020-12-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201203_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postDescription',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postVideo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.video'),
        ),
    ]
