# Generated by Django 3.1.4 on 2020-12-03 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201203_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='userId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userId',
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
