# Generated by Django 3.1.4 on 2020-12-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201203_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postIsVisible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
