# Generated by Django 3.1.4 on 2020-12-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201203_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
