# Generated by Django 3.1.4 on 2020-12-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201203_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyImage',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
        ),
        migrations.AlterField(
            model_name='story',
            name='storyVideo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.video'),
        ),
    ]
