# Generated by Django 3.1.4 on 2020-12-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201203_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='profileId',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uid',
            new_name='userId',
        ),
    ]
