# Generated by Django 3.1.4 on 2020-12-05 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201205_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoURL',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
    ]
